# Jekyll config file

title: Glynnis Ritchie | Product Designer
description: ""
url: "http://glynn.is/"
baseurl: ""
locale: en
analytics: none

navigation:
  - title: Home
    url: /
  - title: Work
    url: /index.html#work
  - title: About
    url: /about.html
  - title: Resume
    url: /glynnis_ritchie_resume.pdf
  - title: Contact
    url: "mailto:glynnis.ritchie+site@gmail.com?subject=Hi there! I just checked out your site"

author:
  name: "Glynnis Ritchie"
  email: "glynnis.ritchie@gmail.com"
  twitter: glynnisritchie
  github: glynnis
  givenName: Glynnis
  familyName: Ritchie

