# Jekyll config file

title: Glynnis Ritchie | UX Designer
url: "http://glynn.is/"
baseurl: "/"
locale: en
analytics: none

navigation:  
  - title: Home
    url: #
  - title: Work
    url: #
  - title: About
    url: about.html
  - title: Resume
    url: #
  - title: Contact
    url: #

author:
  name: "Glynnis Ritchie"
  email: "glynnis.ritchie@gmail.com"
  twitter: glynnisritchie
  github: glynnis
  givenName: Glynnis
  familyName: Ritchie

